"""profile import from external sources

Adds the three things a profile import needs:

* `researcher_profiles.orcid_id` -- the resolved ORCID iD, unique because an
  ORCID identifies exactly one person, so two accounts claiming the same iD is
  a data error worth refusing here rather than reconciling later.
* `profile_imports` -- an audit row per import, so "where did this publication
  come from" is answerable later.
* a trigram index on `publications.title` -- de-duplication compares an
  incoming title against every existing one, and without this the candidate
  scan is a sequential read of the whole register on every import. Written by
  hand: autogenerate compares tables and columns, and never emits an
  expression or operator-class index.

Revision ID: 0022
Revises: 0021
Create Date: 2026-09-28 14:38:33.614059+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0022"
down_revision: str | None = "0021"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "profile_imports",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("orcid_id", sa.String(length=19), nullable=True),
        sa.Column("sources", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("applied_fields", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("works_found", sa.Integer(), server_default="0", nullable=False),
        sa.Column("works_imported", sa.Integer(), server_default="0", nullable=False),
        sa.Column("works_already_known", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_profile_imports_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_profile_imports")),
    )
    op.create_index(
        op.f("ix_profile_imports_user_id"), "profile_imports", ["user_id"], unique=False
    )
    op.add_column("researcher_profiles", sa.Column("orcid_id", sa.String(length=19), nullable=True))
    op.add_column(
        "researcher_profiles",
        sa.Column("orcid_last_imported_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_unique_constraint(
        op.f("uq_researcher_profiles_orcid_id"), "researcher_profiles", ["orcid_id"]
    )
    # ### end Alembic commands ###

    # pg_trgm is already installed by 0005; this is belt and braces for a
    # database built from a partial history.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # De-duplication shortlists candidates with `title % :incoming`, which can
    # only use a GIN index with the trigram operator class.
    op.create_index(
        "ix_publications_title_trgm",
        "publications",
        ["title"],
        postgresql_using="gin",
        postgresql_ops={"title": "gin_trgm_ops"},
    )


def downgrade() -> None:
    op.drop_index("ix_publications_title_trgm", table_name="publications")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq_researcher_profiles_orcid_id"), "researcher_profiles", type_="unique"
    )
    op.drop_column("researcher_profiles", "orcid_last_imported_at")
    op.drop_column("researcher_profiles", "orcid_id")
    op.drop_index(op.f("ix_profile_imports_user_id"), table_name="profile_imports")
    op.drop_table("profile_imports")
    # ### end Alembic commands ###
