"""project milestones with dependencies and at-risk detection

Two tables and two enum values.

`milestones` carries no at-risk column on purpose: risk is derived per request
from the status, the due date and today (app/modules/milestones/risk.py), so
there is nothing here that can go stale between runs of the reminder job.

The two new `notification_type` values are written by hand. Autogenerate
compares tables and columns and never sees enum members -- the same trap that
made migrations 0017 and 0019 hand-written. A test database already stamped at
this revision will not pick them up; rebuild it rather than debugging the
resulting enum error.

Revision ID: 0023
Revises: 0022
Create Date: 2026-09-28 17:25:42.107550+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0023"
down_revision: str | None = "0022"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "milestones",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "in_progress", "done", "cancelled", name="milestone_status"),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status <> 'done' OR completed_at IS NOT NULL", name=op.f("ck_milestones_done_is_dated")
        ),
        sa.ForeignKeyConstraint(
            ["completed_by"],
            ["users.id"],
            name=op.f("fk_milestones_completed_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_milestones_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_milestones")),
        sa.UniqueConstraint("project_id", "position", name="uq_milestones_project_position"),
    )
    op.create_index(op.f("ix_milestones_due_date"), "milestones", ["due_date"], unique=False)
    op.create_index(op.f("ix_milestones_project_id"), "milestones", ["project_id"], unique=False)
    op.create_index(op.f("ix_milestones_status"), "milestones", ["status"], unique=False)
    op.create_table(
        "milestone_dependencies",
        sa.Column("milestone_id", sa.UUID(), nullable=False),
        sa.Column("depends_on_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "milestone_id <> depends_on_id",
            name=op.f("ck_milestone_dependencies_no_self_dependency"),
        ),
        sa.ForeignKeyConstraint(
            ["depends_on_id"],
            ["milestones.id"],
            name=op.f("fk_milestone_dependencies_depends_on_id_milestones"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["milestone_id"],
            ["milestones.id"],
            name=op.f("fk_milestone_dependencies_milestone_id_milestones"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "milestone_id", "depends_on_id", name=op.f("pk_milestone_dependencies")
        ),
    )
    # Enum members, which autogenerate cannot see. IF NOT EXISTS so a
    # partially-migrated database can be brought forward safely.
    op.execute("ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'milestone_due'")
    op.execute("ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'milestone_overdue'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # PostgreSQL cannot drop a value from an enum type, so the two
    # notification_type members added above necessarily stay. They are inert
    # once no code emits them.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("milestone_dependencies")
    op.drop_index(op.f("ix_milestones_status"), table_name="milestones")
    op.drop_index(op.f("ix_milestones_project_id"), table_name="milestones")
    op.drop_index(op.f("ix_milestones_due_date"), table_name="milestones")
    op.drop_table("milestones")
    # ### end Alembic commands ###
