"""nudges

A row per nudge, plus the notification_type value the nudge is delivered as.

The table exists for the cooldown: without a record of when somebody last
chased a thing, "remind them" becomes "generate unlimited notifications for
whoever is senior to you".

The enum value is written by hand -- autogenerate compares tables and columns
and never sees enum members (the trap behind migrations 0017, 0019 and 0023).

Revision ID: 0024
Revises: 0023
Create Date: 2026-09-28 19:01:07.626541+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0024"
down_revision: str | None = "0023"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nudges",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "profile_verification",
                "project_review",
                "booking_approval",
                "application_decision",
                name="nudge_kind",
            ),
            nullable=False,
        ),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("recipient_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["users.id"], name=op.f("fk_nudges_actor_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_nudges")),
    )
    op.create_index(op.f("ix_nudges_actor_id"), "nudges", ["actor_id"], unique=False)
    op.create_index(
        "ix_nudges_actor_kind_entity",
        "nudges",
        ["actor_id", "kind", "entity_id", "created_at"],
        unique=False,
    )
    op.create_index(op.f("ix_nudges_created_at"), "nudges", ["created_at"], unique=False)
    op.execute("ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'nudge_received'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # PostgreSQL cannot drop a value from an enum, so nudge_received stays.
    # It is inert once nothing emits it.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_nudges_created_at"), table_name="nudges")
    op.drop_index("ix_nudges_actor_kind_entity", table_name="nudges")
    op.drop_index(op.f("ix_nudges_actor_id"), table_name="nudges")
    op.drop_table("nudges")
    # ### end Alembic commands ###

    # Dropping the table leaves its enum type behind, which makes a
    # downgrade-then-upgrade fail; same treatment as milestone_status in 0023.
    sa.Enum(name="nudge_kind").drop(op.get_bind(), checkfirst=True)
